// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "37cac048-8d42-4f29-94d3-734fbe241115");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1707);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1618286008);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{564aaacf-d28c-40d1-80f5-892fed9dcd9f}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1618377543636");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1618399143636");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200107212822");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1618377543");
user_pref("browser.slowStartup.averageTime", 6877);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1618377542);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1618286013346");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "79c85d454d2140e88e508080a1bd36be");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200107212822");
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"231aa223-e0f3-4d30-a99b-ad1388c11c0d\",\"formautofill@mozilla.org\":\"59af2dbe-7a88-481a-9e5b-013a021ad9d8\",\"screenshots@mozilla.org\":\"910c93fe-6b63-4b83-b72f-d1352d117f0b\",\"webcompat-reporter@mozilla.org\":\"bbc1223c-497b-4c93-adf0-8db56a9fec87\",\"webcompat@mozilla.org\":\"1445008b-6adf-4a97-b9dd-8a636b0f905b\",\"default-theme@mozilla.org\":\"7d3a6faa-9a62-4189-870a-1a7a008f36db\",\"google@search.mozilla.org\":\"b43f723b-08eb-4334-8dfc-55e0eb245727\",\"amazondotcom@search.mozilla.org\":\"dc2f1671-e53e-4dc2-ba48-ab7b5eb3da25\",\"bing@search.mozilla.org\":\"71a96651-1655-4aee-b758-c4874270873c\",\"ddg@search.mozilla.org\":\"256037e9-f610-469e-8ae1-15a0a55f271e\",\"ebay@search.mozilla.org\":\"32b84b57-8d96-4ed2-8a5a-32499f4e9993\",\"twitter@search.mozilla.org\":\"d6ad8f6e-e2e8-4ec5-bf5e-b9e997fb883f\",\"wikipedia@search.mozilla.org\":\"d17b8ef5-174e-4d1f-9af0-6d9402a29f7e\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "88ca6a8e-593f-4bb3-b4ae-23a3f4a4a1a8");
user_pref("security.sandbox.plugin.tempDirSuffix", "4efaaf82-a565-47f6-919c-0107130ab2e2");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1618377536);
user_pref("toolkit.telemetry.cachedClientID", "a3ba780b-af0b-415b-a37b-2c37d145dbc3");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
